[tool.poetry]
name = "kubos-app"
version = "1.22.0"
description = ""
authors = ["Marshall Culpepper <marshall@xplore.com>"]
license = "Apache Public License v2"
readme = "README.md"
packages = [{include = "kubos_app"}]

[tool.poetry.dependencies]
python = "^3.7"
toml = "^0.10.2"
responses = "^0.22.0"
requests = "^2.31.0"
mock = "^4.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
