[package]
name = "iobc-supervisor-service"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]
edition = "2018"

[dependencies]
juniper =  "0.11"
isis-iobc-supervisor = { path = "../../apis/isis-iobc-supervisor" }
kubos-service = { path = "../kubos-service" }
log = "^0.4.0"
