/*
 * Generated by gdbus-codegen 2.48.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __DB_XML_H__
#define __DB_XML_H__

#include <gio/gio.h>

G_BEGIN_DECLS


G_END_DECLS

#endif /* __DB_XML_H__ */
