[tool.poetry]
name = "i2c"
version = "1.22.0"
description = ""
authors = ["Marshall Culpepper <marshall@xplore.com>"]
license = "Apache Public License v2"
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.7"
toml = "^0.10.2"
responses = "^0.22.0"
requests = "^2.28.1"
mock = "^4.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
