[package]
name = "kubos-build-helper"
version = "0.1.1"
authors = ["Ryan Plauche <ryan@kubos.co>"]
edition = "2018"

[dependencies]
glob = "0.2"
cmake = "0.1"

[package.metadata.release]
release = false
