[package]
name = "rust-uart"
version = "0.2.0"
authors = ["William Greer <wgreer184@gmail.com>", "Catherine Garabedian <catherine@kubos.co>"]

[dependencies]
serial = "0.4.0"
failure = { git = "https://github.com/rust-lang-nursery/failure", branch = "evolution/1.0" }