[package]
name = "comms-service"
version = "0.1.0"
authors = ["William Greer <wgreer184@gmail.com>", "Sam Justice <sam.justice1@gmail.com"]

[dependencies]
failure = "0.1.3"
pnet = "0.21.0"
juniper =  "0.9.2"
byteorder = "1.2.7"
toml = "0.4.10"
