# -*- coding: utf-8 -*-
#
# Kubos documentation build configuration file, created by
# sphinx-quickstart on Fri Apr 21 15:23:32 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import datetime

# List of paths to Kubos python module
# These are injected into the system path so Sphinx can find them
python_modules = [
    'apis/pumpkin-mcu-api',
    'apis/python-app-api',
    'hal/python-hal/i2c'
]

for path in python_modules:
    sys.path.insert(0, os.path.abspath("../%s" % path))

import sphinx_rtd_theme

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = []

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Kubos'
copyright = u'%s, Kubos Corporation' % (datetime.datetime.now().year)
author = u'Kubos'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u'1.16.0+13'
# The full version, including alpha/beta/rc tags.
release = u'1.16.0+13'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = []

html_favicon = "images/kubos_favicon.ico"
html_show_sphinx = False

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'Kubosdoc'

breathe_projects = {
    "gomspace-p31u-api" : "../xml/apis/gomspace-p31u-api",
    "isis-ants-api" : "../xml/apis/isis-ants-api",
    "isis-imtq-api": "../xml/apis/isis-imtq-api",
    "isis-iobc-supervisor" : "../xml/apis/isis-iobc-supervisor",
    "isis-trxvu-api": "../xml/apis/isis-trxvu-api",
    "kubos-hal" : "../xml/hal/kubos-hal",
    "kubos-hal-linux" : "../xml/hal/kubos-hal-linux",
}

extensions += [
    'breathe',
    'sphinx.ext.autodoc',
    'sphinx.ext.todo',
    'sphinx.ext.mathjax',
    'sphinxjsondomain',
    'sphinxcontrib.plantuml'
]
