[package]
name = "rust-beacon-app"
version = "0.1.0"
authors = ["Andrew Cantino <andrew@kubos.com>"]
edition = "2018"

[dependencies]
failure = "0.1.3"
getopts = "0.2"
kubos-app = { path = "../../apis/app-api/rust" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = "^0.4.0"
